# Generated by Django 5.2.8 on 2025-11-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('activity', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, choices=[('Work', 'Work'), ('Exercise', 'Exercise'), ('Learning', 'Learning'), ('Break', 'Break'), ('Personal', 'Personal')], max_length=50)),
                ('energy_level', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Chores',
                'ordering': ['date', 'time_start'],
            },
        ),
    ]
